### PR TITLE
Opencore 0.5.3 templates

### PR DESCRIPTION
**Pull request by Pavo-IM**
Created template config.plist that adhere to the vanilla guide for the Opencore 0.5.3. Also changed the EC0 SSDT from compiled version to dsl version as it should be as an example.

### CODE REVIEW

**Comment by Pavo-IM** [comment]
The conflicting files are replaced with the template plist.

**Comment by IOIIIO** [comment]
I don't see a reason for supplying full pre-made configs. It only encourages laziness and blatant copying of the example.

**Comment by Pavo-IM** [comment]
Its not a full pre-made one, it just has the settings set that adhere to the guide https://khronokernel-2.gitbook.io/opencore-vanilla-desktop-guide/amd-config.plist/amd-config

**Comment by IOIIIO** [comment]
The question is: is that necessary?

Speaking from experience with the Clover side of things, where we do have an example config. People will just take the example config and call it a day. Doing so they don't learn anything, and when it comes to it they are clueless on how to fix issues with their hack when they arise. 

Teach a man how to hackintosh and he'll have a hack for life. Give a man a hack, and he'll complain on your forum that it doesn't work.

**Comment by Pavo-IM** [comment]
I get it, just figured it would help the newbs. Closing PR.

**Pull request closed without merging**
