### PR TITLE
Clover - experimental new patches

### PR DESCRIPTION
**Pull request by fabiosun**
For several months I have been taking care on macOS86.it together with other users about translations of the patches created for the Opencore bootloader for the Clover bootloader.

With the publication of the latest patches in the official github (**thanks guys!**) We managed to synthesize a set of useful patches to make it work as in the Opencore also in Clover bootloader.
And we were successful

I attach them here and hope I can recreate an experimental branch again that we'd love to help cure!
The clover bootloader has several problems, but with patience and a little application you get the same results for the same computer as you get with the Opencore bootloader

**Thanks for your work**

[HS_MOJ_CATA_BS_MR.plist.zip](https://github.com/AMD-OSX/AMD_Vanilla/files/6890415/HS_MOJ_CATA_BS_MR.plist.zip)

algrey - Force cpuid_cores_per_package is set in this set of patches for threadripper 3970x (32 cores--->20 in hexadecimal code

this instead are generic ones:

[patches.plist.zip](https://github.com/AMD-OSX/AMD_Vanilla/files/6890998/patches.plist.zip)

change 00 as said on AMD OSx forum:
https://forum.amd-osx.com/index.php?threads/new-amd-macos-corecount-patch-information.1948/#post-11834

tested with different platform (x370,X570, x399, trx40) and all systems from HighSierra and greater
CPU tested:

3970x
5950x
3950x
3900xt
3600x
2700x
1700x

Some users with Asus / Gigabyte motherboards, may need to use an old patch with the clover bootloader:

**algrey - cpu_topology_sort -disable _x86_validate_topology**

```
<dict>
				<key>Comment</key>
				<string>algrey - cpu_topology_sort -disable _x86_validate_topology</string>
				<key>Count</key>
				<integer>1</integer>
				<key>Disabled</key>
				<false/>
				<key>Find</key>
				<data>
				6AAA//8=
				</data>
				<key>MaskFind</key>
				<data>
				/wAA//8=
				</data>
				<key>MaskReplace</key>
				<data>
				</data>
				<key>MatchOS</key>
				<string>10.13.x,10.14.x,10.15.x,11.x,11,12.x</string>
				<key>Procedure</key>
				<string>_cpu_topology_sort</string>
				<key>Replace</key>
				<data>
				Dx9EAAA=
				</data>
				<key>Skip</key>
				<integer>0</integer>
			</dict>
```

testers:
@fabiosun
@iGpu
@carlo67
@tomnic
@jsl2000

### CODE REVIEW

**Comment by SavageAUS** [comment]
Not sure if this is the right place to submit this but I tried your patches on my X570 with a 3600 and I get a kernel panic.

**Comment by iGPU** [comment]
Did your correct for the core count of your CPU for the first 3 patches ("algrey - Force cpuid") as Shaneee described in ReadMe section of this repository? For the AMD 3600 6-core, the changie would be: "BA**00**0000 0000" to "BA**06**0000 0000", etc. 

(I'm presently on a TRX40 system and have no issues, but can check an X570 with a 3950X tomorrow.)

**Comment by SavageAUS** [comment]
Yeah I changed that, I’ll have another crack tonight.

**Comment by fabiosun** [comment]
> Not sure if this is the right place to submit this but I tried your patches on my X570 with a 3600 and I get a kernel panic.

No I think is not a right place
You can use forum discussion 
And to help you it is better to post a your previous working EFI with clover and a debug when these patches fail for you
Usually is a quirks problem
Or clover modifies your preboot and getosdetection fails

**Comment by fabiosun** [comment]
> Yeah I changed that, I’ll have another crack tonight.

I advice to take a look also here:

https://github.com/CloverHackyColor/CloverBootloader/issues/283

Clover has so many unsolved problems from 5123 version.
But with a lot of patience is possible to have it working.
For me Clover bootloader was useful before Patches "new deal" to have a great reduction of patches I have had to use.
I do not like Clover bootloader, but I like to have also it working in my system.
For this reason I have opened this PR, I think to have also Clover bootloader choice is better for AMD user than to have only a choice!
if you like post here and I will help you as I did for many users with different platform than mine...also other skilled users could help you with your same platform:
https://www.macos86.it/topic/4913-amd-clover-bootloader-monterey-beta-1-234-installation-patches/page/5/#comments

**Comment by fabiosun** [comment]
https://github.com/AMD-OSX/AMD_Vanilla/tree/clover

**Pull request closed without merging**
